/*
===============================================================================
Magnitude Analysis
===============================================================================
Purpose:
    - To quantify data and group results by specific dimensions.
    - For understanding data distribution across categories.

SQL Functions Used:
    - Aggregate Functions: SUM(), COUNT(), AVG()
    - GROUP BY, ORDER BY
===============================================================================
*/

-- Find total customers by countries
SELECT
    country,
    COUNT(*) AS n_customers
FROM gold.dim_customers
GROUP BY
    country
ORDER BY
    n_customers DESC;

-- Find total customers by gender
SELECT
    gender,
    COUNT(*) AS n_customers
FROM gold.dim_customers
GROUP BY
    gender
ORDER BY
    n_customers DESC;

-- Find total products by category
SELECT
    category,
    COUNT(*) AS n_products
FROM gold.dim_products
GROUP BY
    category
ORDER BY
    n_products DESC;

-- What is the average costs in each category?
SELECT
    category,
    ROUND(AVG(cost), 2) AS avg_cost
FROM gold.dim_products
GROUP BY
    category
ORDER BY
    avg_cost DESC;

-- What is the total revenue generated for each category?
SELECT
    COALESCE(p.category, 'Uncategorized') AS category,
    SUM(f.sales_amount) AS revenue_per_category
FROM gold.fact_sales AS f
         LEFT JOIN gold.dim_products AS p ON f.product_key = p.product_key
GROUP BY
    p.category
ORDER BY
    revenue_per_category DESC;

-- What is the total revenue generated by each customer?
SELECT
    dc.customer_id,
    dc.first_name,
    dc.last_name,
    SUM(fs.sales_amount) AS total_revenue
FROM gold.fact_sales AS fs
         LEFT JOIN gold.dim_customers dc ON fs.customer_key = dc.customer_key
GROUP BY
    dc.customer_id,
    dc.first_name,
    dc.last_name
ORDER BY
    total_revenue DESC;

-- What is the distribution of sold items across countries?
SELECT
    dc.country,
    SUM(quantity) AS sold_items
FROM gold.fact_sales AS fs
         LEFT JOIN gold.dim_customers AS dc ON fs.customer_key = dc.customer_key
GROUP BY
    dc.country
ORDER BY
    sold_items DESC;